/* eslint-disable react-refresh/only-export-components */
import React from 'react';

const LANGUAGE_OPTIONS = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'mr', label: 'मराठी' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'ml', label: 'മലയാളം' },
];

const TRANSLATIONS = {
  en: {
    brandName: 'Nagar Alert Hub',
    brandLogoAlt: 'Nagar Alert Hub Logo',
    civicTagline: 'Civic Intelligence Platform',
    home: 'Home',
    features: 'Features',
    whatsapp: 'WhatsApp',
    about: 'About',
    login: 'Login',
    logout: 'Logout',
    switchTheme: 'Switch Theme',
    platform: 'Platform',
    company: 'Company',
    connect: 'Connect',
    howItWorks: 'How it Works',
    forMunicipalities: 'For Municipalities',
    successStories: 'Success Stories',
    aboutUs: 'About Us',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    rightsReserved: '© 2026 Nagar Alert Hub. All rights reserved.',
    madeWithIndia: 'Made with ❤️ in India',
    language: 'Language',
    authForgotPassword: 'Forgot Password?',
    authOtpSendFailed: 'Failed to send verification OTP',
    authCredentialsVerified: 'Credentials verified! Please enter OTP sent to your email.',
    authInvalidCredentials: 'Incorrect email or password. Please try again or register.',
    authTooManyRequests: 'Too many failed attempts. Please reset your password or try again later.',
    authSecureAccessTagline: 'Secure access for citizens & officials',
    authCitizenPortal: 'Citizen Portal',
    authAdminOfficial: 'Admin/Official',
    authEmailAddress: 'Email Address',
    authOfficialIdEmail: 'Official ID / Email',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'Password',
    authPasswordLower: 'password',
    authSecureLogin: 'Secure Login',
    authNewToPlatform: 'New to Nagar Alert Hub?',
    authRegisterAccount: 'Register Account',
    authResetLinkSent: 'Password reset link sent to your email.',
    authSecureResetPortal: 'SECURE RESET PORTAL',
    authYourAccount: 'Your Account.',
    authResetHelpText: 'Follow the simple steps to securely reset your password and continue contributing to your city.',
    authCitizen: 'Citizen',
    authOfficial: 'Official',
    authRegisteredEmail: 'Registered Email Address',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'For security, password reset links are sent via email.',
    authSendResetLink: 'Send Reset Link',
    authRememberedPassword: 'Remembered your password?',
    authBackToLogin: 'Back to Login',
    authResetYour: 'Reset your',
    authJoinAs: 'Join as',
    authFirstNameRequired: 'First Name is required',
    authLastNameRequired: 'Last Name is required',
    authMobileRequired: 'Mobile Number is required',
    authMobileInvalid: 'Enter a valid 10-digit mobile number',
    authEmailRequired: 'Email Address is required',
    authEmailInvalid: 'Enter a valid email address',
    authPasswordRequired: 'Password is required',
    authPasswordMin: 'Minimum 6 characters',
    authPasswordsNoMatch: 'Passwords do not match',
    authAddressRequired: 'Home Address is required',
    authRequired: 'Required',
    authOtpSentWhatsapp: 'OTP sent to your WhatsApp!',
    authOtpAutoSendFailed: 'Could not send WhatsApp OTP automatically.',
    authUserRegistered: 'User Registered Successfully! Welcome,',
    authRegistrationFailed: 'Registration Failed:',
    authGoogleFailed: 'Google Sign In Failed:',
    authGeolocationUnsupported: 'Geolocation not supported',
    authLocationDenied: 'Location access denied',
    authFirstName: 'First Name',
    authFirstNamePlaceholder: 'John',
    authLastName: 'Last Name',
    authLastNamePlaceholder: 'Doe',
    authMobileNumber: 'Mobile Number',
    authMobilePlaceholder: '9876543210',
    authAddress: 'Address',
    authUseCurrentLocation: 'Use Current Location',
    authLocating: 'Locating...',
    authAddressPlaceholder: 'Full Address with City, State',
    authCityPlaceholder: 'City (e.g. Bhilai)',
    authDepartment: 'Department',
    authSelectDepartment: 'Select Department',
    authEmail: 'Email',
    authConfirm: 'Confirm',
    authSignUpNow: 'Sign Up Now',
    authAlreadyMember: 'Already member?',
    authNoVerificationDetails: 'No verification details found. Please try again.',
    authVerificationComplete: 'Verification complete! Redirecting...',
    authSessionStartFailed: 'Failed to start session. Please login manually.',
    authWhatsappOtpSent: 'WhatsApp OTP Sent!',
    authEmailOtpSent: 'Email OTP Sent!',
    authEnterValidOtp: 'Enter valid 6-digit OTP',
    authMobileVerified: 'Mobile Verified Successfully!',
    authEmailVerified: 'Email Verified Successfully!',
    authCityHubAdded: "You've been added to your City Alert Hub!",
    authTwoFactorTitle: 'Two-Factor Authentication',
    authAccountVerificationTitle: 'Account Verification',
    authVerifyEmailSubtitle: 'Please verify your email to access your account.',
    authVerifyMobileEmailSubtitle: 'Please verify your mobile number and email to continue.',
    authMobileVerification: 'Mobile Verification',
    authSending: 'Sending...',
    authSendOtp: 'Send OTP',
    authVerifyMobile: 'Verify Mobile',
    authEmailVerification: 'Email Verification',
    authVerifyEmail: 'Verify Email',
    authSecureOfficialPortal: 'SECURE OFFICIAL PORTAL',
    authLoginHeadingLine1: 'Empowering Citizens,',
    authLoginHeadingLine2: 'Enabling Authorities.',
    authLoginSubtext: 'Join the network building safer, smarter, and more resilient communities through transparent collaboration.',
    authVerified: 'Verified',
    authGovPlatform: 'Gov. Platform',
    authSecurity: 'Security',
    authEncryption: '256-bit Encryption',
    authRegainAccessTo: 'Regain Access to',
    authSecureProcess: 'Secure Process',
    authRegisterHeadingLine1: 'Join the Movement',
    authRegisterHeadingLine2: 'For Better Cities.',
    authRegisterSubtext: 'Sign up today to help your local administration build a cleaner city.',
    heroBadge: 'National Civic Tech Initiative',
    heroHeadingLine1: 'Empowering Citizens.',
    heroHeadingLine2: 'Transforming Cities.',
    heroSubtext: 'Real-time civic issue reporting — powered by WhatsApp & AI.',
    heroPill1: 'No App Required',
    heroPill2: 'Report in 30 Seconds',
    heroPill3: 'AI-Verified Alerts',
    heroPrimaryCta: 'Try on WhatsApp',
    heroSecondaryCta: 'Learn How It Works',
    feature1Title: 'WhatsApp Reporting',
    feature1Tagline: 'No app. No forms.',
    feature1Desc: 'Just send a message and report issues instantly.',
    feature2Title: 'AI Smart Routing',
    feature2Tagline: 'Right dept. First time.',
    feature2Desc: 'AI removes duplicates and routes issues accurately.',
    feature3Title: 'Live Tracking',
    feature3Tagline: 'Real-time updates',
    feature3Desc: 'Track issue progress directly in WhatsApp.',
    poweredByNagar: 'Powered by Nagar Intelligence',
    statCitizens: 'Citizens',
    statResolved: 'Resolved',
    statResponse: 'Response',
    statCities: 'Cities',
    featuresBadge: 'Why Nagar Alert Hub?',
    featuresHeading: 'Built for Citizens. Trusted by Cities.',
    featuresSubtext: 'A simple, transparent civic reporting system that actually works.',
    howBadge: 'Simple Process',
    howHeading: 'How It Works',
    howSubtext: 'Democratizing civic reporting with a platform everyone already knows how to use.',
    howStep1Title: 'Spot an Issue',
    howStep1Desc: 'Notice a civic problem like a pothole, uncollected garbage, or a broken streetlight in your neighborhood.',
    howStep2Title: 'Send a WhatsApp Message',
    howStep2Desc: "Simply send 'Hi' to our dedicated WhatsApp number (+91 73196 62244). No apps to download.",
    howStep3Title: 'Share Details',
    howStep3Desc: 'Our AI bot will guide you to share a photo and your location. It takes less than 30 seconds.',
    howStep4Title: 'Information Verification',
    howStep4Desc: 'Our AI verifies the location and categorizes the issue automatically to prevent duplicates.',
    howStep5Title: 'Resolution',
    howStep5Desc: "The request is routed to the on-field municipal team. You get updates at every step until it's fixed.",
    howDemoTitle: 'See it in action',
    howDemoSubtext: 'Watch how easy it is to report an issue. The entire conversation happens in your local language.',
    howDemoCta: 'Start Chat on WhatsApp',
    howDemoPlaceholder: 'Demo Video Placeholder',
    municipalitiesBadge: 'For City Administrations',
    municipalitiesHeading: 'Transform Your City Governance',
    municipalitiesSubtext: 'Equip your municipality with AI-driven insights, real-time citizen reporting, and efficient workforce management tools.',
    municipalitiesCardTitle: 'Command Center Dashboard',
    municipalitiesCardSubtext: 'A unified view of all city issues, categorized by urgency and location. Dispatch teams with a single click.',
    municipalitiesPoint1: 'Real-time Issue Heatmaps',
    municipalitiesPoint2: 'Automated Ticket Assignment',
    municipalitiesPoint3: 'SLA Tracking & Reports',
    municipalitiesCtaTitle: 'Partner with Nagar Alert Hub',
    municipalitiesCtaSubtext: 'Join 15+ pioneering cities that have improved their response times by 60%.',
    municipalitiesCtaButton: 'Schedule a Demo',
    successBadge: 'Impact Stories',
    successHeading: 'Success Across India',
    story1City: 'Indore',
    story1Title: 'Achieving #1 Cleanest City Status with Community Reporting',
    story1Stat: '45% faster cleanup',
    story1Desc: 'How Indore Municipal Corporation leveraged Nagar Alert Hub to crowdsource cleanliness audits.',
    story2City: 'Pune',
    story2Title: 'Fixing 500+ Potholes in a Single Monsoon Week',
    story2Stat: 'Zero duplicates',
    story2Desc: "Pune's road department used our AI-deduplication to focus on fixing roads rather than filtering data.",
    story3City: 'Chandigarh',
    story3Title: 'Smart Street Lighting: A Brighter, Safer City',
    story3Stat: '99% uptime',
    story3Desc: 'Automated reporting integration for street light outages reduced downtime significantly.',
    whatsappBadge: 'WhatsApp First Experience',
    whatsappHeadingLine1: 'Report City Issues',
    whatsappHeadingLine2: 'Just Like Chatting.',
    whatsappSubtext: 'No apps. No paperwork. Our AI-powered WhatsApp assistant helps you report civic issues in under 30 seconds.',
    whatsappPoint1Title: 'No App Required',
    whatsappPoint1Desc: 'Works directly on WhatsApp',
    whatsappPoint2Title: 'Location & Photo',
    whatsappPoint2Desc: 'Share instantly in chat',
    whatsappPoint3Title: 'AI Verification',
    whatsappPoint3Desc: 'Smart duplicate detection',
    whatsappPoint4Title: 'Live Updates',
    whatsappPoint4Desc: 'Status in your chat window',
    whatsappCta: 'Try Demo on WhatsApp',
    whatsappChatAgent: 'Nagar Helper',
    whatsappChatStatus: 'Online',
    whatsappChatLine1: 'Hello 👋 Welcome to Nagar Alert Hub.',
    whatsappChatLine2: 'There’s a broken streetlight on Main Road.',
    whatsappChatLine3: 'Thanks! Please share a photo or location 📸📍',
    privacyLastUpdated: 'Last updated: January 2026',
    privacySection1Title: '1. Information We Collect',
    privacySection1Text: 'We collect information that you provide directly to us, such as when you submit a report via WhatsApp, creating a user account, or communicate with us. This may include your phone number, location data associated with incident reports, and images you upload.',
    privacySection2Title: '2. How We Use Your Information',
    privacySection2Intro: 'We use the information we collect to:',
    privacyPoint1: 'Verify and process civic incident reports.',
    privacyPoint2: 'Coordinate with municipal authorities for resolution.',
    privacyPoint3: 'Send you status updates regarding your reports.',
    privacyPoint4: 'Improve our AI verification models.',
    privacySection3Title: '3. Data Sharing',
    privacySection3Text: 'We share incident data with relevant municipal corporations and service providers to facilitate resolution. We do not sell your personal data to advertisers.',
    termsWelcome: 'Welcome to Nagar Alert Hub.',
    termsSection1Title: '1. Acceptance of Terms',
    termsSection1Text: 'By accessing or using our services, you agree to be bound by these terms. If you do not agree to these terms, you may not use the services.',
    termsSection2Title: '2. User Conduct',
    termsSection2Intro: 'You agree to use our platform responsibly. You will NOT:',
    termsPoint1: 'Submit false or misleading reports.',
    termsPoint2: 'Use the service for harassment or illegal activities.',
    termsPoint3: 'Attempt to interfere with the proper working of the API or platform.',
    termsFinalText: 'Nagar Alert Hub acts as an intermediary. We are not responsible for the actual resolution of issues, which depends on the respective municipal authorities.',
  },
  hi: {
    brandName: 'नगर अलर्ट हब',
    brandLogoAlt: 'नगर अलर्ट हब लोगो',
    civicTagline: 'सिविक इंटेलिजेंस प्लेटफ़ॉर्म',
    home: 'होम',
    features: 'फ़ीचर्स',
    whatsapp: 'व्हाट्सऐप',
    about: 'हमारे बारे में',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    switchTheme: 'थीम बदलें',
    platform: 'प्लेटफ़ॉर्म',
    company: 'कंपनी',
    connect: 'जुड़ें',
    howItWorks: 'यह कैसे काम करता है',
    forMunicipalities: 'नगर पालिकाओं के लिए',
    successStories: 'सफलता की कहानियाँ',
    aboutUs: 'हमारे बारे में',
    privacyPolicy: 'गोपनीयता नीति',
    termsOfService: 'सेवा की शर्तें',
    rightsReserved: '© 2026 नगर Alert Hub. सर्वाधिकार सुरक्षित।',
    madeWithIndia: 'भारत में ❤️ के साथ बनाया गया',
    language: 'भाषा',
    authForgotPassword: 'पासवर्ड भूल गए?',
    authOtpSendFailed: 'सत्यापन OTP भेजने में विफल',
    authCredentialsVerified: 'आपकी जानकारी सत्यापित हो गई! कृपया ईमेल पर भेजा गया OTP दर्ज करें।',
    authInvalidCredentials: 'गलत ईमेल या पासवर्ड। कृपया दोबारा प्रयास करें या रजिस्टर करें।',
    authTooManyRequests: 'बहुत अधिक असफल प्रयास। कृपया पासवर्ड रीसेट करें या बाद में प्रयास करें।',
    authSecureAccessTagline: 'नागरिकों और अधिकारियों के लिए सुरक्षित प्रवेश',
    authCitizenPortal: 'नागरिक पोर्टल',
    authAdminOfficial: 'एडमिन/अधिकारी',
    authEmailAddress: 'ईमेल पता',
    authOfficialIdEmail: 'अधिकारी आईडी / ईमेल',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'पासवर्ड',
    authPasswordLower: 'पासवर्ड',
    authSecureLogin: 'सुरक्षित लॉगिन',
    authNewToPlatform: 'Nagar Alert Hub पर नए हैं?',
    authRegisterAccount: 'खाता रजिस्टर करें',
    authResetLinkSent: 'पासवर्ड रीसेट लिंक आपके ईमेल पर भेज दिया गया है।',
    authSecureResetPortal: 'सुरक्षित रीसेट पोर्टल',
    authYourAccount: 'आपका खाता।',
    authResetHelpText: 'अपना पासवर्ड सुरक्षित तरीके से रीसेट करने के लिए सरल चरणों का पालन करें।',
    authCitizen: 'नागरिक',
    authOfficial: 'अधिकारी',
    authRegisteredEmail: 'पंजीकृत ईमेल पता',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'सुरक्षा के लिए, पासवर्ड रीसेट लिंक ईमेल द्वारा भेजे जाते हैं।',
    authSendResetLink: 'रीसेट लिंक भेजें',
    authRememberedPassword: 'पासवर्ड याद आ गया?',
    authBackToLogin: 'लॉगिन पर वापस जाएँ',
    authResetYour: 'अपना',
    authJoinAs: 'के रूप में जुड़ें',
    authFirstNameRequired: 'पहला नाम आवश्यक है',
    authLastNameRequired: 'अंतिम नाम आवश्यक है',
    authMobileRequired: 'मोबाइल नंबर आवश्यक है',
    authMobileInvalid: 'मान्य 10-अंकों का मोबाइल नंबर दर्ज करें',
    authEmailRequired: 'ईमेल पता आवश्यक है',
    authEmailInvalid: 'मान्य ईमेल पता दर्ज करें',
    authPasswordRequired: 'पासवर्ड आवश्यक है',
    authPasswordMin: 'कम से कम 6 अक्षर',
    authPasswordsNoMatch: 'पासवर्ड मेल नहीं खाते',
    authAddressRequired: 'घर का पता आवश्यक है',
    authRequired: 'आवश्यक',
    authOtpSentWhatsapp: 'OTP आपके WhatsApp पर भेज दिया गया है!',
    authOtpAutoSendFailed: 'WhatsApp OTP स्वतः नहीं भेजा जा सका।',
    authUserRegistered: 'उपयोगकर्ता सफलतापूर्वक पंजीकृत! स्वागत है,',
    authRegistrationFailed: 'पंजीकरण विफल:',
    authGoogleFailed: 'Google साइन-इन विफल:',
    authGeolocationUnsupported: 'जियोलोकेशन समर्थित नहीं है',
    authLocationDenied: 'लोकेशन अनुमति अस्वीकार की गई',
    authFirstName: 'पहला नाम',
    authFirstNamePlaceholder: 'राहुल',
    authLastName: 'अंतिम नाम',
    authLastNamePlaceholder: 'शर्मा',
    authMobileNumber: 'मोबाइल नंबर',
    authMobilePlaceholder: '9876543210',
    authAddress: 'पता',
    authUseCurrentLocation: 'वर्तमान लोकेशन का उपयोग करें',
    authLocating: 'लोकेशन ढूंढी जा रही है...',
    authAddressPlaceholder: 'शहर/राज्य सहित पूरा पता',
    authCityPlaceholder: 'शहर (जैसे भिलाई)',
    authDepartment: 'विभाग',
    authSelectDepartment: 'विभाग चुनें',
    authEmail: 'ईमेल',
    authConfirm: 'पुष्टि',
    authSignUpNow: 'अभी साइन अप करें',
    authAlreadyMember: 'पहले से सदस्य हैं?',
    authNoVerificationDetails: 'सत्यापन विवरण नहीं मिला। कृपया पुनः प्रयास करें।',
    authVerificationComplete: 'सत्यापन पूर्ण! रीडायरेक्ट किया जा रहा है...',
    authSessionStartFailed: 'सेशन शुरू नहीं हो सका। कृपया मैन्युअली लॉगिन करें।',
    authWhatsappOtpSent: 'WhatsApp OTP भेज दिया गया!',
    authEmailOtpSent: 'ईमेल OTP भेज दिया गया!',
    authEnterValidOtp: 'मान्य 6-अंकों का OTP दर्ज करें',
    authMobileVerified: 'मोबाइल सफलतापूर्वक सत्यापित हुआ!',
    authEmailVerified: 'ईमेल सफलतापूर्वक सत्यापित हुआ!',
    authCityHubAdded: 'आपको City Alert Hub में जोड़ दिया गया है!',
    authTwoFactorTitle: 'टू-फैक्टर ऑथेंटिकेशन',
    authAccountVerificationTitle: 'खाता सत्यापन',
    authVerifyEmailSubtitle: 'अपने खाते तक पहुँचने के लिए कृपया ईमेल सत्यापित करें।',
    authVerifyMobileEmailSubtitle: 'आगे बढ़ने के लिए मोबाइल नंबर और ईमेल सत्यापित करें।',
    authMobileVerification: 'मोबाइल सत्यापन',
    authSending: 'भेजा जा रहा है...',
    authSendOtp: 'OTP भेजें',
    authVerifyMobile: 'मोबाइल सत्यापित करें',
    authEmailVerification: 'ईमेल सत्यापन',
    authVerifyEmail: 'ईमेल सत्यापित करें',
    authSecureOfficialPortal: 'सुरक्षित अधिकारी पोर्टल',
    authLoginHeadingLine1: 'नागरिकों को सशक्त बनाना,',
    authLoginHeadingLine2: 'अधिकारियों को सक्षम बनाना।',
    authLoginSubtext: 'सुरक्षित, स्मार्ट और लचीले समुदाय बनाने वाले नेटवर्क से जुड़ें।',
    authVerified: 'सत्यापित',
    authGovPlatform: 'सरकारी प्लेटफ़ॉर्म',
    authSecurity: 'सुरक्षा',
    authEncryption: '256-बिट एन्क्रिप्शन',
    authRegainAccessTo: 'दोबारा पहुँच प्राप्त करें',
    authSecureProcess: 'सुरक्षित प्रक्रिया',
    authRegisterHeadingLine1: 'आंदोलन से जुड़ें',
    authRegisterHeadingLine2: 'बेहतर शहरों के लिए।',
    authRegisterSubtext: 'स्वच्छ शहर बनाने में स्थानीय प्रशासन की मदद के लिए आज ही रजिस्टर करें।',
    heroBadge: 'राष्ट्रीय नागरिक तकनीक पहल',
    heroHeadingLine1: 'नागरिकों को सशक्त बनाना।',
    heroHeadingLine2: 'शहरों को बदलना।',
    heroSubtext: 'रियल-टाइम नागरिक समस्या रिपोर्टिंग — WhatsApp और AI द्वारा संचालित।',
    heroPill1: 'ऐप की जरूरत नहीं',
    heroPill2: '30 सेकंड में रिपोर्ट',
    heroPill3: 'AI सत्यापित अलर्ट',
    heroPrimaryCta: 'WhatsApp पर आज़माएँ',
    heroSecondaryCta: 'यह कैसे काम करता है',
    feature1Title: 'व्हाट्सऐप रिपोर्टिंग',
    feature1Tagline: 'न ऐप, न फॉर्म।',
    feature1Desc: 'बस संदेश भेजें और तुरंत समस्या रिपोर्ट करें।',
    feature2Title: 'AI स्मार्ट रूटिंग',
    feature2Tagline: 'सही विभाग, पहली बार में।',
    feature2Desc: 'AI डुप्लिकेट हटाकर समस्याओं को सही विभाग तक पहुँचाता है।',
    feature3Title: 'लाइव ट्रैकिंग',
    feature3Tagline: 'रियल-टाइम अपडेट',
    feature3Desc: 'WhatsApp में सीधे समस्या की प्रगति ट्रैक करें।',
    poweredByNagar: 'Nagar Intelligence द्वारा संचालित',
    statCitizens: 'नागरिक',
    statResolved: 'समाधान',
    statResponse: 'प्रतिक्रिया',
    statCities: 'शहर',
    featuresBadge: 'Nagar Alert Hub क्यों?',
    featuresHeading: 'नागरिकों के लिए निर्मित। शहरों द्वारा विश्वसनीय।',
    featuresSubtext: 'एक सरल और पारदर्शी नागरिक रिपोर्टिंग प्रणाली जो सच में काम करती है।',
    howBadge: 'सरल प्रक्रिया',
    howHeading: 'यह कैसे काम करता है',
    howSubtext: 'नागरिक रिपोर्टिंग को ऐसे प्लेटफ़ॉर्म से आसान बनाना जिसे हर कोई पहले से जानता है।',
    howStep1Title: 'समस्या पहचानें',
    howStep1Desc: 'अपने क्षेत्र में गड्ढा, कचरा या टूटी स्ट्रीट लाइट जैसी समस्या देखें।',
    howStep2Title: 'WhatsApp संदेश भेजें',
    howStep2Desc: "हमारे WhatsApp नंबर (+91 73196 62244) पर 'Hi' भेजें। कोई ऐप डाउनलोड नहीं।",
    howStep3Title: 'विवरण साझा करें',
    howStep3Desc: 'हमारा AI बॉट फोटो और लोकेशन साझा करने में मार्गदर्शन करेगा। इसमें 30 सेकंड से कम समय लगता है।',
    howStep4Title: 'जानकारी सत्यापन',
    howStep4Desc: 'हमारा AI लोकेशन सत्यापित कर समस्या को स्वतः वर्गीकृत करता है और डुप्लिकेट रोकता है।',
    howStep5Title: 'समाधान',
    howStep5Desc: 'अनुरोध संबंधित नगरपालिका टीम तक भेजा जाता है और आपको हर चरण पर अपडेट मिलते हैं।',
    howDemoTitle: 'इसे काम करते देखें',
    howDemoSubtext: 'समस्या रिपोर्ट करना कितना आसान है देखें। पूरी बातचीत आपकी स्थानीय भाषा में होती है।',
    howDemoCta: 'WhatsApp पर चैट शुरू करें',
    howDemoPlaceholder: 'डेमो वीडियो प्लेसहोल्डर',
    municipalitiesBadge: 'शहर प्रशासन के लिए',
    municipalitiesHeading: 'अपने शहर का शासन बदलें',
    municipalitiesSubtext: 'AI-आधारित अंतर्दृष्टि, रियल-टाइम रिपोर्टिंग और कुशल प्रबंधन उपकरणों से अपनी नगरपालिका को सशक्त बनाएं।',
    municipalitiesCardTitle: 'कमांड सेंटर डैशबोर्ड',
    municipalitiesCardSubtext: 'सभी शहर समस्याओं का एकीकृत दृश्य। एक क्लिक में टीम भेजें।',
    municipalitiesPoint1: 'रियल-टाइम इश्यू हीटमैप्स',
    municipalitiesPoint2: 'स्वचालित टिकट असाइनमेंट',
    municipalitiesPoint3: 'SLA ट्रैकिंग और रिपोर्ट्स',
    municipalitiesCtaTitle: 'Nagar Alert Hub के साथ साझेदारी करें',
    municipalitiesCtaSubtext: '15+ अग्रणी शहरों से जुड़ें जिन्होंने प्रतिक्रिया समय में 60% सुधार किया है।',
    municipalitiesCtaButton: 'डेमो शेड्यूल करें',
    successBadge: 'प्रभाव की कहानियाँ',
    successHeading: 'भारत भर की सफलता',
    story1City: 'इंदौर',
    story1Title: 'समुदाय रिपोर्टिंग से #1 स्वच्छ शहर का दर्जा',
    story1Stat: '45% तेज सफाई',
    story1Desc: 'इंदौर नगर निगम ने सामुदायिक रिपोर्टिंग से स्वच्छता ऑडिट को बेहतर बनाया।',
    story2City: 'पुणे',
    story2Title: 'एक सप्ताह में 500+ गड्ढों का समाधान',
    story2Stat: 'शून्य डुप्लिकेट',
    story2Desc: 'AI डीडुप्लिकेशन से पुणे टीम ने फ़िल्टरिंग की जगह समाधान पर ध्यान दिया।',
    story3City: 'चंडीगढ़',
    story3Title: 'स्मार्ट स्ट्रीट लाइटिंग: उज्ज्वल और सुरक्षित शहर',
    story3Stat: '99% अपटाइम',
    story3Desc: 'स्वचालित रिपोर्टिंग एकीकरण से स्ट्रीट लाइट डाउनटाइम में कमी आई।',
    whatsappBadge: 'WhatsApp आधारित अनुभव',
    whatsappHeadingLine1: 'शहर की समस्याएँ रिपोर्ट करें',
    whatsappHeadingLine2: 'जैसे चैट कर रहे हों।',
    whatsappSubtext: 'न ऐप, न कागज़ी काम। हमारा AI-सक्षम WhatsApp सहायक 30 सेकंड में रिपोर्ट करने में मदद करता है।',
    whatsappPoint1Title: 'ऐप की जरूरत नहीं',
    whatsappPoint1Desc: 'सीधे WhatsApp पर काम करता है',
    whatsappPoint2Title: 'लोकेशन और फोटो',
    whatsappPoint2Desc: 'चैट में तुरंत साझा करें',
    whatsappPoint3Title: 'AI सत्यापन',
    whatsappPoint3Desc: 'स्मार्ट डुप्लिकेट पहचान',
    whatsappPoint4Title: 'लाइव अपडेट',
    whatsappPoint4Desc: 'आपकी चैट विंडो में स्थिति',
    whatsappCta: 'WhatsApp डेमो आज़माएँ',
    whatsappChatAgent: 'Nagar Helper',
    whatsappChatStatus: 'ऑनलाइन',
    whatsappChatLine1: 'नमस्ते 👋 Nagar Alert Hub में आपका स्वागत है।',
    whatsappChatLine2: 'मेन रोड पर स्ट्रीट लाइट खराब है।',
    whatsappChatLine3: 'धन्यवाद! कृपया फोटो या लोकेशन साझा करें 📸📍',
    privacyLastUpdated: 'अंतिम अपडेट: जनवरी 2026',
    privacySection1Title: '1. हम कौन-सी जानकारी एकत्र करते हैं',
    privacySection1Text: 'हम वह जानकारी एकत्र करते हैं जो आप सीधे देते हैं, जैसे WhatsApp रिपोर्ट, खाता बनाना या हमसे संपर्क करना। इसमें फोन नंबर, लोकेशन और अपलोड की गई छवियाँ शामिल हो सकती हैं।',
    privacySection2Title: '2. हम आपकी जानकारी का उपयोग कैसे करते हैं',
    privacySection2Intro: 'हम आपकी जानकारी का उपयोग इन कार्यों के लिए करते हैं:',
    privacyPoint1: 'नागरिक समस्या रिपोर्ट की जाँच और प्रक्रिया।',
    privacyPoint2: 'समाधान के लिए नगरपालिका से समन्वय।',
    privacyPoint3: 'आपकी रिपोर्ट की स्थिति अपडेट भेजना।',
    privacyPoint4: 'हमारे AI सत्यापन मॉडल में सुधार।',
    privacySection3Title: '3. डेटा साझा करना',
    privacySection3Text: 'समाधान के लिए हम संबंधित नगर निगम और सेवा प्रदाताओं के साथ डेटा साझा करते हैं। हम आपका व्यक्तिगत डेटा विज्ञापनदाताओं को नहीं बेचते।',
    termsWelcome: 'Nagar Alert Hub में आपका स्वागत है।',
    termsSection1Title: '1. शर्तों की स्वीकृति',
    termsSection1Text: 'हमारी सेवाओं का उपयोग करके आप इन शर्तों से सहमत होते हैं। असहमति होने पर सेवा का उपयोग न करें।',
    termsSection2Title: '2. उपयोगकर्ता आचरण',
    termsSection2Intro: 'आप प्लेटफ़ॉर्म का जिम्मेदारी से उपयोग करेंगे। आप नहीं करेंगे:',
    termsPoint1: 'झूठी या भ्रामक रिपोर्ट जमा करना।',
    termsPoint2: 'उत्पीड़न या अवैध गतिविधि के लिए सेवा का उपयोग।',
    termsPoint3: 'API या प्लेटफ़ॉर्म के कार्य में बाधा डालने का प्रयास।',
    termsFinalText: 'Nagar Alert Hub एक मध्यस्थ के रूप में कार्य करता है। वास्तविक समाधान संबंधित नगरपालिका प्राधिकरणों पर निर्भर है।',
  },
  pa: {
    brandName: 'ਨਗਰ ਅਲਰਟ ਹੱਬ',
    brandLogoAlt: 'ਨਗਰ ਅਲਰਟ ਹੱਬ ਲੋਗੋ',
    civicTagline: 'ਸਿਵਿਕ ਇੰਟੈਲੀਜੈਂਸ ਪਲੇਟਫਾਰਮ',
    home: 'ਮੁੱਖ',
    features: 'ਖਾਸੀਅਤਾਂ',
    whatsapp: 'ਵਟਸਐਪ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    login: 'ਲੌਗਇਨ',
    logout: 'ਲੌਗਆਉਟ',
    switchTheme: 'ਥੀਮ ਬਦਲੋ',
    platform: 'ਪਲੇਟਫਾਰਮ',
    company: 'ਕੰਪਨੀ',
    connect: 'ਜੁੜੋ',
    howItWorks: 'ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ',
    forMunicipalities: 'ਨਗਰ ਨਿਗਮਾਂ ਲਈ',
    successStories: 'ਕਾਮਯਾਬੀ ਦੀਆਂ ਕਹਾਣੀਆਂ',
    aboutUs: 'ਸਾਡੇ ਬਾਰੇ',
    privacyPolicy: 'ਗੋਪਨੀਯਤਾ ਨੀਤੀ',
    termsOfService: 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ',
    rightsReserved: '© 2026 Nagar Alert Hub. ਸਭ ਹੱਕ ਰਾਖਵੇਂ।',
    madeWithIndia: 'ਭਾਰਤ ਵਿੱਚ ❤️ ਨਾਲ ਬਣਾਇਆ',
    language: 'ਭਾਸ਼ਾ',
    authForgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ?',
    authOtpSendFailed: 'ਪ੍ਰਮਾਣਿਕਰਨ OTP ਭੇਜਣ ਵਿੱਚ ਅਸਫਲ',
    authCredentialsVerified: 'ਤੁਹਾਡੇ ਵੇਰਵੇ ਪੱਕੇ ਹੋ ਗਏ! ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ’ਤੇ ਆਇਆ OTP ਦਾਖਲ ਕਰੋ।',
    authInvalidCredentials: 'ਗਲਤ ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਰਜਿਸਟਰ ਕਰੋ।',
    authTooManyRequests: 'ਬਹੁਤ ਜ਼ਿਆਦਾ ਅਸਫਲ ਕੋਸ਼ਿਸ਼ਾਂ। ਕਿਰਪਾ ਕਰਕੇ ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ ਜਾਂ ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    authSecureAccessTagline: 'ਨਾਗਰਿਕਾਂ ਅਤੇ ਅਧਿਕਾਰੀਆਂ ਲਈ ਸੁਰੱਖਿਅਤ ਪਹੁੰਚ',
    authCitizenPortal: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    authAdminOfficial: 'ਐਡਮਿਨ/ਅਧਿਕਾਰੀ',
    authEmailAddress: 'ਈਮੇਲ ਪਤਾ',
    authOfficialIdEmail: 'ਅਧਿਕਾਰੀ ਆਈਡੀ / ਈਮੇਲ',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'ਪਾਸਵਰਡ',
    authPasswordLower: 'ਪਾਸਵਰਡ',
    authSecureLogin: 'ਸੁਰੱਖਿਅਤ ਲੌਗਇਨ',
    authNewToPlatform: 'Nagar Alert Hub ’ਤੇ ਨਵੇਂ ਹੋ?',
    authRegisterAccount: 'ਖਾਤਾ ਰਜਿਸਟਰ ਕਰੋ',
    authResetLinkSent: 'ਪਾਸਵਰਡ ਰੀਸੈਟ ਲਿੰਕ ਤੁਹਾਡੀ ਈਮੇਲ ’ਤੇ ਭੇਜ ਦਿੱਤਾ ਗਿਆ ਹੈ।',
    authSecureResetPortal: 'ਸੁਰੱਖਿਅਤ ਰੀਸੈਟ ਪੋਰਟਲ',
    authYourAccount: 'ਤੁਹਾਡਾ ਖਾਤਾ।',
    authResetHelpText: 'ਆਪਣਾ ਪਾਸਵਰਡ ਸੁਰੱਖਿਅਤ ਤਰੀਕੇ ਨਾਲ ਰੀਸੈਟ ਕਰਨ ਲਈ ਸਧਾਰਣ ਕਦਮਾਂ ਦੀ ਪਾਲਣਾ ਕਰੋ।',
    authCitizen: 'ਨਾਗਰਿਕ',
    authOfficial: 'ਅਧਿਕਾਰੀ',
    authRegisteredEmail: 'ਰਜਿਸਟਰ ਕੀਤਾ ਈਮੇਲ ਪਤਾ',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'ਸੁਰੱਖਿਆ ਲਈ, ਰੀਸੈਟ ਲਿੰਕ ਈਮੇਲ ਰਾਹੀਂ ਭੇਜੇ ਜਾਂਦੇ ਹਨ।',
    authSendResetLink: 'ਰੀਸੈਟ ਲਿੰਕ ਭੇਜੋ',
    authRememberedPassword: 'ਪਾਸਵਰਡ ਯਾਦ ਆ ਗਿਆ?',
    authBackToLogin: 'ਲੌਗਇਨ ਵੱਲ ਵਾਪਸ',
    authResetYour: 'ਤੁਹਾਡਾ',
    authJoinAs: 'ਵਜੋਂ ਸ਼ਾਮਲ ਹੋਵੋ',
    authFirstNameRequired: 'ਪਹਿਲਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
    authLastNameRequired: 'ਆਖਰੀ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ',
    authMobileRequired: 'ਮੋਬਾਈਲ ਨੰਬਰ ਲਾਜ਼ਮੀ ਹੈ',
    authMobileInvalid: 'ਵੈਧ 10-ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਾਖਲ ਕਰੋ',
    authEmailRequired: 'ਈਮੇਲ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
    authEmailInvalid: 'ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਾਖਲ ਕਰੋ',
    authPasswordRequired: 'ਪਾਸਵਰਡ ਲਾਜ਼ਮੀ ਹੈ',
    authPasswordMin: 'ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ',
    authPasswordsNoMatch: 'ਪਾਸਵਰਡ ਮਿਲਦੇ ਨਹੀਂ',
    authAddressRequired: 'ਘਰ ਦਾ ਪਤਾ ਲਾਜ਼ਮੀ ਹੈ',
    authRequired: 'ਲਾਜ਼ਮੀ',
    authOtpSentWhatsapp: 'OTP ਤੁਹਾਡੇ WhatsApp ’ਤੇ ਭੇਜਿਆ ਗਿਆ!',
    authOtpAutoSendFailed: 'WhatsApp OTP ਆਟੋਮੈਟਿਕ ਭੇਜਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ।',
    authUserRegistered: 'ਯੂਜ਼ਰ ਸਫਲਤਾਪੂਰਵਕ ਰਜਿਸਟਰ ਹੋ ਗਿਆ! ਸੁਆਗਤ ਹੈ,',
    authRegistrationFailed: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਸਫਲ:',
    authGoogleFailed: 'Google ਸਾਈਨ-ਇਨ ਅਸਫਲ:',
    authGeolocationUnsupported: 'Geolocation ਸਮਰਥਿਤ ਨਹੀਂ',
    authLocationDenied: 'ਲੋਕੇਸ਼ਨ ਦੀ ਆਗਿਆ ਨਾਕਾਰ ਦਿੱਤੀ ਗਈ',
    authFirstName: 'ਪਹਿਲਾ ਨਾਮ',
    authFirstNamePlaceholder: 'ਅਮਨ',
    authLastName: 'ਆਖਰੀ ਨਾਮ',
    authLastNamePlaceholder: 'ਸਿੰਘ',
    authMobileNumber: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    authMobilePlaceholder: '9876543210',
    authAddress: 'ਪਤਾ',
    authUseCurrentLocation: 'ਮੌਜੂਦਾ ਸਥਿਤੀ ਵਰਤੋ',
    authLocating: 'ਲੋਕੇਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    authAddressPlaceholder: 'ਸ਼ਹਿਰ/ਰਾਜ ਸਮੇਤ ਪੂਰਾ ਪਤਾ',
    authCityPlaceholder: 'ਸ਼ਹਿਰ (ਜਿਵੇਂ ਲੁਧਿਆਣਾ)',
    authDepartment: 'ਵਿਭਾਗ',
    authSelectDepartment: 'ਵਿਭਾਗ ਚੁਣੋ',
    authEmail: 'ਈਮੇਲ',
    authConfirm: 'ਪੁਸ਼ਟੀ',
    authSignUpNow: 'ਹੁਣੇ ਰਜਿਸਟਰ ਕਰੋ',
    authAlreadyMember: 'ਪਹਿਲਾਂ ਹੀ ਮੈਂਬਰ ਹੋ?',
    authNoVerificationDetails: 'ਪ੍ਰਮਾਣਿਕਰਨ ਵੇਰਵੇ ਨਹੀਂ ਮਿਲੇ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    authVerificationComplete: 'ਪ੍ਰਮਾਣਿਕਰਨ ਪੂਰਾ! ਰੀਡਾਇਰੈਕਟ ਕੀਤਾ ਜਾ ਰਿਹਾ ਹੈ...',
    authSessionStartFailed: 'ਸੈਸ਼ਨ ਸ਼ੁਰੂ ਨਹੀਂ ਹੋ ਸਕਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਮੈਨੁਅਲੀ ਲੌਗਇਨ ਕਰੋ।',
    authWhatsappOtpSent: 'WhatsApp OTP ਭੇਜਿਆ ਗਿਆ!',
    authEmailOtpSent: 'ਈਮੇਲ OTP ਭੇਜਿਆ ਗਿਆ!',
    authEnterValidOtp: 'ਵੈਧ 6-ਅੰਕਾਂ ਵਾਲਾ OTP ਦਾਖਲ ਕਰੋ',
    authMobileVerified: 'ਮੋਬਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਵੇਰੀਫਾਈ ਹੋ ਗਿਆ!',
    authEmailVerified: 'ਈਮੇਲ ਸਫਲਤਾਪੂਰਵਕ ਵੇਰੀਫਾਈ ਹੋ ਗਿਆ!',
    authCityHubAdded: 'ਤੁਹਾਨੂੰ City Alert Hub ਵਿੱਚ ਸ਼ਾਮਲ ਕਰ ਦਿੱਤਾ ਗਿਆ ਹੈ!',
    authTwoFactorTitle: 'ਦੋ-ਪੜਾਅ ਪ੍ਰਮਾਣਿਕਰਨ',
    authAccountVerificationTitle: 'ਖਾਤਾ ਪ੍ਰਮਾਣਿਕਰਨ',
    authVerifyEmailSubtitle: 'ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਪਹੁੰਚ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਵੇਰੀਫਾਈ ਕਰੋ।',
    authVerifyMobileEmailSubtitle: 'ਅੱਗੇ ਵਧਣ ਲਈ ਮੋਬਾਈਲ ਨੰਬਰ ਅਤੇ ਈਮੇਲ ਵੇਰੀਫਾਈ ਕਰੋ।',
    authMobileVerification: 'ਮੋਬਾਈਲ ਪ੍ਰਮਾਣਿਕਰਨ',
    authSending: 'ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...',
    authSendOtp: 'OTP ਭੇਜੋ',
    authVerifyMobile: 'ਮੋਬਾਈਲ ਵੇਰੀਫਾਈ ਕਰੋ',
    authEmailVerification: 'ਈਮੇਲ ਪ੍ਰਮਾਣਿਕਰਨ',
    authVerifyEmail: 'ਈਮੇਲ ਵੇਰੀਫਾਈ ਕਰੋ',
    authSecureOfficialPortal: 'ਸੁਰੱਖਿਅਤ ਅਧਿਕਾਰੀ ਪੋਰਟਲ',
    authLoginHeadingLine1: 'ਨਾਗਰਿਕਾਂ ਨੂੰ ਸਸ਼ਕਤ ਕਰਨਾ,',
    authLoginHeadingLine2: 'ਅਧਿਕਾਰੀਆਂ ਨੂੰ ਸਮਰੱਥ ਬਣਾਉਣਾ।',
    authLoginSubtext: 'ਸੁਰੱਖਿਅਤ, ਸਮਾਰਟ ਅਤੇ ਮਜ਼ਬੂਤ ਕਮਿਊਨਿਟੀਆਂ ਬਣਾਉਣ ਵਾਲੇ ਨੈੱਟਵਰਕ ਨਾਲ ਜੁੜੋ।',
    authVerified: 'ਵੇਰੀਫਾਈਡ',
    authGovPlatform: 'ਸਰਕਾਰੀ ਪਲੇਟਫਾਰਮ',
    authSecurity: 'ਸੁਰੱਖਿਆ',
    authEncryption: '256-ਬਿਟ ਇਨਕ੍ਰਿਪਸ਼ਨ',
    authRegainAccessTo: 'ਮੁੜ ਪਹੁੰਚ ਪ੍ਰਾਪਤ ਕਰੋ',
    authSecureProcess: 'ਸੁਰੱਖਿਅਤ ਪ੍ਰਕਿਰਿਆ',
    authRegisterHeadingLine1: 'ਅਭਿਆਨ ਨਾਲ ਜੁੜੋ',
    authRegisterHeadingLine2: 'ਵਧੀਆ ਸ਼ਹਿਰਾਂ ਲਈ।',
    authRegisterSubtext: 'ਆਪਣੇ ਸਥਾਨਕ ਪ੍ਰਸ਼ਾਸਨ ਨੂੰ ਸਾਫ਼ ਸ਼ਹਿਰ ਬਣਾਉਣ ਵਿੱਚ ਮਦਦ ਕਰਨ ਲਈ ਅੱਜ ਹੀ ਰਜਿਸਟਰ ਕਰੋ।',
  },
  bn: {
    brandName: 'নগর অ্যালার্ট হাব',
    brandLogoAlt: 'নগর অ্যালার্ট হাব লোগো',
    civicTagline: 'সিভিক ইন্টেলিজেন্স প্ল্যাটফর্ম',
    home: 'হোম',
    features: 'ফিচার',
    whatsapp: 'হোয়াটসঅ্যাপ',
    about: 'আমাদের সম্পর্কে',
    login: 'লগইন',
    logout: 'লগআউট',
    switchTheme: 'থিম পরিবর্তন করুন',
    platform: 'প্ল্যাটফর্ম',
    company: 'কোম্পানি',
    connect: 'সংযোগ',
    howItWorks: 'কীভাবে কাজ করে',
    forMunicipalities: 'মিউনিসিপ্যালিটির জন্য',
    successStories: 'সাফল্যের গল্প',
    aboutUs: 'আমাদের সম্পর্কে',
    privacyPolicy: 'গোপনীয়তা নীতি',
    termsOfService: 'পরিষেবার শর্তাবলি',
    rightsReserved: '© 2026 Nagar Alert Hub. সর্বস্বত্ব সংরক্ষিত।',
    madeWithIndia: 'ভারতে ❤️ দিয়ে তৈরি',
    language: 'ভাষা',
    authForgotPassword: 'পাসওয়ার্ড ভুলে গেছেন?',
    authOtpSendFailed: 'যাচাইকরণ OTP পাঠাতে ব্যর্থ',
    authCredentialsVerified: 'আপনার তথ্য যাচাই হয়েছে! অনুগ্রহ করে ইমেইলে পাঠানো OTP লিখুন।',
    authInvalidCredentials: 'ভুল ইমেইল বা পাসওয়ার্ড। আবার চেষ্টা করুন বা রেজিস্টার করুন।',
    authTooManyRequests: 'অনেকবার ব্যর্থ চেষ্টা হয়েছে। পাসওয়ার্ড রিসেট করুন বা পরে চেষ্টা করুন।',
    authSecureAccessTagline: 'নাগরিক ও কর্মকর্তাদের জন্য নিরাপদ প্রবেশাধিকার',
    authCitizenPortal: 'নাগরিক পোর্টাল',
    authAdminOfficial: 'অ্যাডমিন/কর্মকর্তা',
    authEmailAddress: 'ইমেইল ঠিকানা',
    authOfficialIdEmail: 'কর্মকর্তা আইডি / ইমেইল',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'পাসওয়ার্ড',
    authPasswordLower: 'পাসওয়ার্ড',
    authSecureLogin: 'নিরাপদ লগইন',
    authNewToPlatform: 'Nagar Alert Hub-এ নতুন?',
    authRegisterAccount: 'অ্যাকাউন্ট রেজিস্টার করুন',
    authResetLinkSent: 'পাসওয়ার্ড রিসেট লিংক আপনার ইমেইলে পাঠানো হয়েছে।',
    authSecureResetPortal: 'নিরাপদ রিসেট পোর্টাল',
    authYourAccount: 'আপনার অ্যাকাউন্ট।',
    authResetHelpText: 'পাসওয়ার্ড নিরাপদে রিসেট করতে সহজ ধাপগুলো অনুসরণ করুন।',
    authCitizen: 'নাগরিক',
    authOfficial: 'কর্মকর্তা',
    authRegisteredEmail: 'নিবন্ধিত ইমেইল ঠিকানা',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'নিরাপত্তার জন্য রিসেট লিংক ইমেইলের মাধ্যমে পাঠানো হয়।',
    authSendResetLink: 'রিসেট লিংক পাঠান',
    authRememberedPassword: 'পাসওয়ার্ড মনে পড়েছে?',
    authBackToLogin: 'লগইনে ফিরে যান',
    authResetYour: 'আপনার',
    authJoinAs: 'হিসেবে যোগ দিন',
    authFirstNameRequired: 'নাম আবশ্যক',
    authLastNameRequired: 'পদবি আবশ্যক',
    authMobileRequired: 'মোবাইল নম্বর আবশ্যক',
    authMobileInvalid: 'সঠিক ১০-সংখ্যার মোবাইল নম্বর দিন',
    authEmailRequired: 'ইমেইল ঠিকানা আবশ্যক',
    authEmailInvalid: 'সঠিক ইমেইল ঠিকানা দিন',
    authPasswordRequired: 'পাসওয়ার্ড আবশ্যক',
    authPasswordMin: 'কমপক্ষে ৬ অক্ষর',
    authPasswordsNoMatch: 'পাসওয়ার্ড মেলে না',
    authAddressRequired: 'বাড়ির ঠিকানা আবশ্যক',
    authRequired: 'আবশ্যক',
    authOtpSentWhatsapp: 'OTP আপনার WhatsApp-এ পাঠানো হয়েছে!',
    authOtpAutoSendFailed: 'WhatsApp OTP স্বয়ংক্রিয়ভাবে পাঠানো যায়নি।',
    authUserRegistered: 'ব্যবহারকারী সফলভাবে নিবন্ধিত! স্বাগতম,',
    authRegistrationFailed: 'নিবন্ধন ব্যর্থ:',
    authGoogleFailed: 'Google সাইন-ইন ব্যর্থ:',
    authGeolocationUnsupported: 'Geolocation সমর্থিত নয়',
    authLocationDenied: 'লোকেশন অনুমতি প্রত্যাখ্যাত',
    authFirstName: 'নাম',
    authFirstNamePlaceholder: 'রাহুল',
    authLastName: 'পদবি',
    authLastNamePlaceholder: 'দাস',
    authMobileNumber: 'মোবাইল নম্বর',
    authMobilePlaceholder: '9876543210',
    authAddress: 'ঠিকানা',
    authUseCurrentLocation: 'বর্তমান লোকেশন ব্যবহার করুন',
    authLocating: 'লোকেশন খোঁজা হচ্ছে...',
    authAddressPlaceholder: 'শহর/রাজ্যসহ পূর্ণ ঠিকানা',
    authCityPlaceholder: 'শহর (যেমন দুর্গাপুর)',
    authDepartment: 'বিভাগ',
    authSelectDepartment: 'বিভাগ নির্বাচন করুন',
    authEmail: 'ইমেইল',
    authConfirm: 'নিশ্চিত করুন',
    authSignUpNow: 'এখনই সাইন আপ করুন',
    authAlreadyMember: 'ইতিমধ্যেই সদস্য?',
    authNoVerificationDetails: 'যাচাইকরণের তথ্য পাওয়া যায়নি। আবার চেষ্টা করুন।',
    authVerificationComplete: 'যাচাইকরণ সম্পূর্ণ! রিডাইরেক্ট করা হচ্ছে...',
    authSessionStartFailed: 'সেশন শুরু করা যায়নি। অনুগ্রহ করে ম্যানুয়ালি লগইন করুন।',
    authWhatsappOtpSent: 'WhatsApp OTP পাঠানো হয়েছে!',
    authEmailOtpSent: 'ইমেইল OTP পাঠানো হয়েছে!',
    authEnterValidOtp: 'সঠিক ৬-সংখ্যার OTP লিখুন',
    authMobileVerified: 'মোবাইল সফলভাবে যাচাই হয়েছে!',
    authEmailVerified: 'ইমেইল সফলভাবে যাচাই হয়েছে!',
    authCityHubAdded: 'আপনাকে City Alert Hub-এ যুক্ত করা হয়েছে!',
    authTwoFactorTitle: 'টু-ফ্যাক্টর অথেনটিকেশন',
    authAccountVerificationTitle: 'অ্যাকাউন্ট যাচাইকরণ',
    authVerifyEmailSubtitle: 'অ্যাকাউন্ট অ্যাক্সেসের জন্য আপনার ইমেইল যাচাই করুন।',
    authVerifyMobileEmailSubtitle: 'চালিয়ে যেতে মোবাইল নম্বর ও ইমেইল যাচাই করুন।',
    authMobileVerification: 'মোবাইল যাচাইকরণ',
    authSending: 'পাঠানো হচ্ছে...',
    authSendOtp: 'OTP পাঠান',
    authVerifyMobile: 'মোবাইল যাচাই করুন',
    authEmailVerification: 'ইমেইল যাচাইকরণ',
    authVerifyEmail: 'ইমেইল যাচাই করুন',
    authSecureOfficialPortal: 'নিরাপদ অফিসিয়াল পোর্টাল',
    authLoginHeadingLine1: 'নাগরিকদের ক্ষমতায়ন,',
    authLoginHeadingLine2: 'কর্তৃপক্ষকে সক্ষম করা।',
    authLoginSubtext: 'নিরাপদ, স্মার্ট ও সহনশীল কমিউনিটি গড়ার নেটওয়ার্কে যোগ দিন।',
    authVerified: 'যাচাইকৃত',
    authGovPlatform: 'সরকারি প্ল্যাটফর্ম',
    authSecurity: 'নিরাপত্তা',
    authEncryption: '256-বিট এনক্রিপশন',
    authRegainAccessTo: 'পুনরায় প্রবেশাধিকার পান',
    authSecureProcess: 'নিরাপদ প্রক্রিয়া',
    authRegisterHeadingLine1: 'আন্দোলনে যোগ দিন',
    authRegisterHeadingLine2: 'উন্নত শহরের জন্য।',
    authRegisterSubtext: 'পরিষ্কার শহর গড়তে স্থানীয় প্রশাসনকে সাহায্য করতে আজই সাইন আপ করুন।',
  },
  mr: {
    brandName: 'नगर अलर्ट हब',
    brandLogoAlt: 'नगर अलर्ट हब लोगो',
    civicTagline: 'नागरी बुद्धिमत्ता प्लॅटफॉर्म',
    home: 'मुख्यपृष्ठ',
    features: 'वैशिष्ट्ये',
    whatsapp: 'व्हॉट्सअॅप',
    about: 'आमच्याबद्दल',
    login: 'लॉगिन',
    logout: 'लॉगआउट',
    switchTheme: 'थीम बदला',
    platform: 'प्लॅटफॉर्म',
    company: 'कंपनी',
    connect: 'जोडा',
    howItWorks: 'हे कसे कार्य करते',
    forMunicipalities: 'महानगरपालिकांसाठी',
    successStories: 'यशोगाथा',
    aboutUs: 'आमच्याबद्दल',
    privacyPolicy: 'गोपनीयता धोरण',
    termsOfService: 'सेवेच्या अटी',
    rightsReserved: '© 2026 Nagar Alert Hub. सर्व हक्क राखीव.',
    madeWithIndia: 'भारतामध्ये ❤️ सह तयार केले',
    language: 'भाषा',
    authForgotPassword: 'पासवर्ड विसरलात?',
    authOtpSendFailed: 'सत्यापन OTP पाठवण्यात अयशस्वी',
    authCredentialsVerified: 'क्रेडेन्शियल्स सत्यापित झाले! कृपया ईमेलवर आलेला OTP टाका.',
    authInvalidCredentials: 'ईमेल किंवा पासवर्ड चुकीचा आहे. कृपया पुन्हा प्रयत्न करा किंवा नोंदणी करा.',
    authTooManyRequests: 'खूप अयशस्वी प्रयत्न झाले. कृपया पासवर्ड रीसेट करा किंवा नंतर प्रयत्न करा.',
    authSecureAccessTagline: 'नागरिक आणि अधिकाऱ्यांसाठी सुरक्षित प्रवेश',
    authCitizenPortal: 'नागरिक पोर्टल',
    authAdminOfficial: 'प्रशासक/अधिकारी',
    authEmailAddress: 'ईमेल पत्ता',
    authOfficialIdEmail: 'अधिकृत आयडी / ईमेल',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'पासवर्ड',
    authPasswordLower: 'पासवर्ड',
    authSecureLogin: 'सुरक्षित लॉगिन',
    authNewToPlatform: 'Nagar Alert Hub मध्ये नवीन आहात?',
    authRegisterAccount: 'खाते नोंदणी करा',
    authResetLinkSent: 'पासवर्ड रीसेट लिंक तुमच्या ईमेलवर पाठवली आहे.',
    authSecureResetPortal: 'सुरक्षित रीसेट पोर्टल',
    authYourAccount: 'तुमचे खाते.',
    authResetHelpText: 'तुमचा पासवर्ड सुरक्षितरीत्या रीसेट करण्यासाठी सोप्या पायऱ्या पूर्ण करा.',
    authCitizen: 'नागरिक',
    authOfficial: 'अधिकारी',
    authRegisteredEmail: 'नोंदणीकृत ईमेल पत्ता',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'सुरक्षेसाठी पासवर्ड रीसेट लिंक ईमेलद्वारे पाठवली जाते.',
    authSendResetLink: 'रीसेट लिंक पाठवा',
    authRememberedPassword: 'पासवर्ड आठवला?',
    authBackToLogin: 'लॉगिनकडे परत जा',
    authResetYour: 'तुमचा',
    authJoinAs: 'म्हणून सामील व्हा',
    authFirstNameRequired: 'पहिले नाव आवश्यक आहे',
    authLastNameRequired: 'आडनाव आवश्यक आहे',
    authMobileRequired: 'मोबाइल क्रमांक आवश्यक आहे',
    authMobileInvalid: 'वैध 10-अंकी मोबाइल क्रमांक टाका',
    authEmailRequired: 'ईमेल पत्ता आवश्यक आहे',
    authEmailInvalid: 'वैध ईमेल पत्ता टाका',
    authPasswordRequired: 'पासवर्ड आवश्यक आहे',
    authPasswordMin: 'किमान 6 अक्षरे',
    authPasswordsNoMatch: 'पासवर्ड जुळत नाहीत',
    authAddressRequired: 'घरचा पत्ता आवश्यक आहे',
    authRequired: 'आवश्यक',
    authOtpSentWhatsapp: 'OTP तुमच्या WhatsApp वर पाठवला!',
    authOtpAutoSendFailed: 'WhatsApp OTP आपोआप पाठवता आला नाही.',
    authUserRegistered: 'वापरकर्ता यशस्वीरित्या नोंदणीकृत! स्वागत आहे,',
    authRegistrationFailed: 'नोंदणी अयशस्वी:',
    authGoogleFailed: 'Google साइन इन अयशस्वी:',
    authGeolocationUnsupported: 'जिओलोकेशन समर्थित नाही',
    authLocationDenied: 'लोकेशन प्रवेश नाकारला',
    authFirstName: 'पहिले नाव',
    authFirstNamePlaceholder: 'राम',
    authLastName: 'आडनाव',
    authLastNamePlaceholder: 'शर्मा',
    authMobileNumber: 'मोबाइल क्रमांक',
    authMobilePlaceholder: '9876543210',
    authAddress: 'पत्ता',
    authUseCurrentLocation: 'सध्याचे लोकेशन वापरा',
    authLocating: 'शोधत आहे...',
    authAddressPlaceholder: 'पूर्ण पत्ता शहर/राज्यासह',
    authCityPlaceholder: 'शहर (उदा. भिलाई)',
    authDepartment: 'विभाग',
    authSelectDepartment: 'विभाग निवडा',
    authEmail: 'ईमेल',
    authConfirm: 'पुष्टी',
    authSignUpNow: 'आत्ता नोंदणी करा',
    authAlreadyMember: 'आधीपासून सदस्य आहात?',
    authNoVerificationDetails: 'सत्यापन तपशील आढळले नाहीत. कृपया पुन्हा प्रयत्न करा.',
    authVerificationComplete: 'सत्यापन पूर्ण! रीडायरेक्ट करत आहे...',
    authSessionStartFailed: 'सेशन सुरू करण्यात अयशस्वी. कृपया हाताने लॉगिन करा.',
    authWhatsappOtpSent: 'WhatsApp OTP पाठवला!',
    authEmailOtpSent: 'ईमेल OTP पाठवला!',
    authEnterValidOtp: 'वैध 6-अंकी OTP टाका',
    authMobileVerified: 'मोबाइल सत्यापित झाला!',
    authEmailVerified: 'ईमेल सत्यापित झाला!',
    authCityHubAdded: 'तुम्हाला City Alert Hub मध्ये जोडले गेले आहे!',
    authTwoFactorTitle: 'दुहेरी-घटक प्रमाणीकरण',
    authAccountVerificationTitle: 'खाते सत्यापन',
    authVerifyEmailSubtitle: 'तुमच्या खात्यात प्रवेशासाठी ईमेल सत्यापित करा.',
    authVerifyMobileEmailSubtitle: 'पुढे जाण्यासाठी मोबाइल क्रमांक आणि ईमेल सत्यापित करा.',
    authMobileVerification: 'मोबाइल सत्यापन',
    authSending: 'पाठवत आहे...',
    authSendOtp: 'OTP पाठवा',
    authVerifyMobile: 'मोबाइल सत्यापित करा',
    authEmailVerification: 'ईमेल सत्यापन',
    authVerifyEmail: 'ईमेल सत्यापित करा',
    authSecureOfficialPortal: 'सुरक्षित अधिकारी पोर्टल',
    authLoginHeadingLine1: 'नागरिकांना सक्षम करणे,',
    authLoginHeadingLine2: 'अधिकाऱ्यांना समर्थ बनवणे.',
    authLoginSubtext: 'सुरक्षित, स्मार्ट आणि सक्षम समुदाय तयार करणाऱ्या नेटवर्कमध्ये सहभागी व्हा.',
    authVerified: 'सत्यापित',
    authGovPlatform: 'शासकीय प्लॅटफॉर्म',
    authSecurity: 'सुरक्षा',
    authEncryption: '256-बिट एन्क्रिप्शन',
    authRegainAccessTo: 'पुन्हा प्रवेश मिळवा',
    authSecureProcess: 'सुरक्षित प्रक्रिया',
    authRegisterHeadingLine1: 'चळवळीत सहभागी व्हा',
    authRegisterHeadingLine2: 'उत्तम शहरांसाठी.',
    authRegisterSubtext: 'स्वच्छ शहर उभारण्यासाठी स्थानिक प्रशासनाला मदत करण्यासाठी आजच नोंदणी करा.',
  },
  te: {
    brandName: 'నగర్ అలర్ట్ హబ్',
    brandLogoAlt: 'నగర్ అలర్ట్ హబ్ లోగో',
    civicTagline: 'పౌర మేధస్సు వేదిక',
    home: 'హోమ్',
    features: 'ఫీచర్లు',
    whatsapp: 'వాట్సాప్',
    about: 'మా గురించి',
    login: 'లాగిన్',
    logout: 'లాగ్ఔట్',
    switchTheme: 'థీమ్ మార్చండి',
    platform: 'వేదిక',
    company: 'కంపెనీ',
    connect: 'కనెక్ట్',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    forMunicipalities: 'మున్సిపాలిటీల కోసం',
    successStories: 'విజయ కథలు',
    aboutUs: 'మా గురించి',
    privacyPolicy: 'గోప్యతా విధానం',
    termsOfService: 'సేవా నిబంధనలు',
    rightsReserved: '© 2026 Nagar Alert Hub. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.',
    madeWithIndia: 'భారతదేశంలో ❤️ తో రూపొందించబడింది',
    language: 'భాష',
    authForgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
    authOtpSendFailed: 'ధృవీకరణ OTP పంపడంలో విఫలమైంది',
    authCredentialsVerified: 'మీ వివరాలు ధృవీకరించబడ్డాయి! దయచేసి ఇమెయిల్‌కు వచ్చిన OTP నమోదు చేయండి.',
    authInvalidCredentials: 'తప్పు ఇమెయిల్ లేదా పాస్‌వర్డ్. మళ్లీ ప్రయత్నించండి లేదా నమోదు చేసుకోండి.',
    authTooManyRequests: 'చాలా విఫల ప్రయత్నాలు జరిగాయి. పాస్‌వర్డ్ రీసెట్ చేయండి లేదా తరువాత ప్రయత్నించండి.',
    authSecureAccessTagline: 'పౌరులు మరియు అధికారుల కోసం సురక్షిత ప్రాప్తి',
    authCitizenPortal: 'పౌరుల పోర్టల్',
    authAdminOfficial: 'అడ్మిన్/అధికారి',
    authEmailAddress: 'ఇమెయిల్ చిరునామా',
    authOfficialIdEmail: 'అధికారి ఐడి / ఇమెయిల్',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'పాస్‌వర్డ్',
    authPasswordLower: 'పాస్‌వర్డ్',
    authSecureLogin: 'సురక్షిత లాగిన్',
    authNewToPlatform: 'Nagar Alert Hub కు కొత్తవారా?',
    authRegisterAccount: 'ఖాతా నమోదు చేయండి',
    authResetLinkSent: 'పాస్‌వర్డ్ రీసెట్ లింక్ మీ ఇమెయిల్‌కు పంపబడింది.',
    authSecureResetPortal: 'సురక్షిత రీసెట్ పోర్టల్',
    authYourAccount: 'మీ ఖాతా.',
    authResetHelpText: 'మీ పాస్‌వర్డ్‌ను సురక్షితంగా రీసెట్ చేయడానికి సరళమైన దశలను అనుసరించండి.',
    authCitizen: 'పౌరుడు',
    authOfficial: 'అధికారి',
    authRegisteredEmail: 'నమోదిత ఇమెయిల్ చిరునామా',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'భద్రత కోసం, రీసెట్ లింకులు ఇమెయిల్ ద్వారా పంపబడతాయి.',
    authSendResetLink: 'రీసెట్ లింక్ పంపు',
    authRememberedPassword: 'పాస్‌వర్డ్ గుర్తొచ్చిందా?',
    authBackToLogin: 'లాగిన్‌కు తిరిగి వెళ్లండి',
    authResetYour: 'మీ',
    authJoinAs: 'గా చేరండి',
    authFirstNameRequired: 'మొదటి పేరు అవసరం',
    authLastNameRequired: 'చివరి పేరు అవసరం',
    authMobileRequired: 'మొబైల్ నంబర్ అవసరం',
    authMobileInvalid: 'సరైన 10 అంకెల మొబైల్ నంబర్ నమోదు చేయండి',
    authEmailRequired: 'ఇమెయిల్ చిరునామా అవసరం',
    authEmailInvalid: 'సరైన ఇమెయిల్ చిరునామా నమోదు చేయండి',
    authPasswordRequired: 'పాస్‌వర్డ్ అవసరం',
    authPasswordMin: 'కనీసం 6 అక్షరాలు',
    authPasswordsNoMatch: 'పాస్‌వర్డ్లు సరిపోలడం లేదు',
    authAddressRequired: 'ఇంటి చిరునామా అవసరం',
    authRequired: 'అవసరం',
    authOtpSentWhatsapp: 'OTP మీ WhatsApp కి పంపబడింది!',
    authOtpAutoSendFailed: 'WhatsApp OTP ఆటోమేటిక్‌గా పంపలేకపోయాం.',
    authUserRegistered: 'వినియోగదారు విజయవంతంగా నమోదు అయ్యారు! స్వాగతం,',
    authRegistrationFailed: 'నమోదు విఫలమైంది:',
    authGoogleFailed: 'Google సైన్-ఇన్ విఫలమైంది:',
    authGeolocationUnsupported: 'Geolocation మద్దతు లేదు',
    authLocationDenied: 'లోకేషన్ అనుమతి నిరాకరించబడింది',
    authFirstName: 'మొదటి పేరు',
    authFirstNamePlaceholder: 'రాహుల్',
    authLastName: 'చివరి పేరు',
    authLastNamePlaceholder: 'కుమార్',
    authMobileNumber: 'మొబైల్ నంబర్',
    authMobilePlaceholder: '9876543210',
    authAddress: 'చిరునామా',
    authUseCurrentLocation: 'ప్రస్తుత లోకేషన్ ఉపయోగించండి',
    authLocating: 'లోకేషన్ కనుగొంటోంది...',
    authAddressPlaceholder: 'నగరం/రాష్ట్రంతో పూర్తి చిరునామా',
    authCityPlaceholder: 'నగరం (ఉదా. విజయవాడ)',
    authDepartment: 'శాఖ',
    authSelectDepartment: 'శాఖను ఎంచుకోండి',
    authEmail: 'ఇమెయిల్',
    authConfirm: 'నిర్ధారించండి',
    authSignUpNow: 'ఇప్పుడు సైన్ అప్ చేయండి',
    authAlreadyMember: 'ఇప్పటికే సభ్యుడా?',
    authNoVerificationDetails: 'ధృవీకరణ వివరాలు కనబడలేదు. దయచేసి మళ్లీ ప్రయత్నించండి.',
    authVerificationComplete: 'ధృవీకరణ పూర్తైంది! మళ్లించబడుతోంది...',
    authSessionStartFailed: 'సెషన్ ప్రారంభించలేకపోయాం. దయచేసి మాన్యువల్‌గా లాగిన్ చేయండి.',
    authWhatsappOtpSent: 'WhatsApp OTP పంపబడింది!',
    authEmailOtpSent: 'ఇమెయిల్ OTP పంపబడింది!',
    authEnterValidOtp: 'సరైన 6 అంకెల OTP నమోదు చేయండి',
    authMobileVerified: 'మొబైల్ విజయవంతంగా ధృవీకరించబడింది!',
    authEmailVerified: 'ఇమెయిల్ విజయవంతంగా ధృవీకరించబడింది!',
    authCityHubAdded: 'మీరు City Alert Hub కు జోడించబడ్డారు!',
    authTwoFactorTitle: 'టూ-ఫ్యాక్టర్ ధృవీకరణ',
    authAccountVerificationTitle: 'ఖాతా ధృవీకరణ',
    authVerifyEmailSubtitle: 'మీ ఖాతాకు ప్రాప్తి కోసం మీ ఇమెయిల్‌ను ధృవీకరించండి.',
    authVerifyMobileEmailSubtitle: 'కొనసాగడానికి మొబైల్ నంబర్ మరియు ఇమెయిల్‌ను ధృవీకరించండి.',
    authMobileVerification: 'మొబైల్ ధృవీకరణ',
    authSending: 'పంపుతోంది...',
    authSendOtp: 'OTP పంపు',
    authVerifyMobile: 'మొబైల్ ధృవీకరించండి',
    authEmailVerification: 'ఇమెయిల్ ధృవీకరణ',
    authVerifyEmail: 'ఇమెయిల్ ధృవీకరించండి',
    authSecureOfficialPortal: 'సురక్షిత అధికారిక పోర్టల్',
    authLoginHeadingLine1: 'పౌరులను శక్తివంతం చేస్తూ,',
    authLoginHeadingLine2: 'అధికారులను సాధికారితం చేస్తోంది.',
    authLoginSubtext: 'సురక్షిత, తెలివైన మరియు స్థిరమైన సమాజాలను నిర్మించే నెట్‌వర్క్‌లో చేరండి.',
    authVerified: 'ధృవీకరించబడినది',
    authGovPlatform: 'ప్రభుత్వ వేదిక',
    authSecurity: 'భద్రత',
    authEncryption: '256-బిట్ ఎన్క్రిప్షన్',
    authRegainAccessTo: 'మళ్లీ ప్రాప్తి పొందండి',
    authSecureProcess: 'సురక్షిత ప్రక్రియ',
    authRegisterHeadingLine1: 'మూవ్‌మెంట్‌లో చేరండి',
    authRegisterHeadingLine2: 'మెరుగైన నగరాల కోసం.',
    authRegisterSubtext: 'శుభ్రమైన నగరాన్ని నిర్మించడంలో స్థానిక పరిపాలనకు సహాయం చేయడానికి ఈరోజే సైన్ అప్ చేయండి.',
  },
  ta: {
    brandName: 'நகர் அலர்ட் ஹப்',
    brandLogoAlt: 'நகர் அலர்ட் ஹப் லோகோ',
    civicTagline: 'குடிமை நுண்ணறிவு தளம்',
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    whatsapp: 'வாட்ஸ்அப்',
    about: 'எங்களை பற்றி',
    login: 'உள்நுழை',
    logout: 'வெளியேறு',
    switchTheme: 'தீம் மாற்று',
    platform: 'தளம்',
    company: 'நிறுவனம்',
    connect: 'இணைப்பு',
    howItWorks: 'இது எப்படி செயல்படுகிறது',
    forMunicipalities: 'நகராட்சிகளுக்காக',
    successStories: 'வெற்றி கதைகள்',
    aboutUs: 'எங்களை பற்றி',
    privacyPolicy: 'தனியுரிமைக் கொள்கை',
    termsOfService: 'சேவை விதிமுறைகள்',
    rightsReserved: '© 2026 Nagar Alert Hub. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    madeWithIndia: 'இந்தியாவில் ❤️ உடன் உருவாக்கப்பட்டது',
    language: 'மொழி',
    authForgotPassword: 'கடவுச்சொல் மறந்துவிட்டதா?',
    authOtpSendFailed: 'சரிபார்ப்பு OTP அனுப்ப முடியவில்லை',
    authCredentialsVerified: 'உங்கள் விவரங்கள் சரிபார்க்கப்பட்டன! மின்னஞ்சலுக்கு வந்த OTP-ஐ உள்ளிடவும்.',
    authInvalidCredentials: 'தவறான மின்னஞ்சல் அல்லது கடவுச்சொல். மீண்டும் முயற்சிக்கவும் அல்லது பதிவு செய்யவும்.',
    authTooManyRequests: 'பல தோல்வியுற்ற முயற்சிகள். கடவுச்சொல்லை மீட்டமைக்கவும் அல்லது பின்னர் முயற்சிக்கவும்.',
    authSecureAccessTagline: 'குடிமக்கள் மற்றும் அதிகாரிகளுக்கான பாதுகாப்பான அணுகல்',
    authCitizenPortal: 'குடிமக்கள் தளம்',
    authAdminOfficial: 'நிர்வாகி/அதிகாரி',
    authEmailAddress: 'மின்னஞ்சல் முகவரி',
    authOfficialIdEmail: 'அதிகாரி ஐடி / மின்னஞ்சல்',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'கடவுச்சொல்',
    authPasswordLower: 'கடவுச்சொல்',
    authSecureLogin: 'பாதுகாப்பான உள்நுழைவு',
    authNewToPlatform: 'Nagar Alert Hub-இல் புதியவரா?',
    authRegisterAccount: 'கணக்கு பதிவு செய்யவும்',
    authResetLinkSent: 'கடவுச்சொல் மீட்டமைப்பு இணைப்பு மின்னஞ்சலுக்கு அனுப்பப்பட்டது.',
    authSecureResetPortal: 'பாதுகாப்பான ரீசெட் போர்டல்',
    authYourAccount: 'உங்கள் கணக்கு.',
    authResetHelpText: 'உங்கள் கடவுச்சொல்லை பாதுகாப்பாக மீட்டமைக்க எளிய படிகளை பின்பற்றவும்.',
    authCitizen: 'குடிமக்கள்',
    authOfficial: 'அதிகாரி',
    authRegisteredEmail: 'பதிவுசெய்யப்பட்ட மின்னஞ்சல் முகவரி',
    authResetSecurityNote: 'பாதுகாப்புக்காக மீட்டமைப்பு இணைப்புகள் மின்னஞ்சல் வழியாக அனுப்பப்படும்.',
    authSendResetLink: 'மீட்டமைப்பு இணைப்பை அனுப்பு',
    authRememberedPassword: 'கடவுச்சொல் நினைவுக்கு வந்ததா?',
    authBackToLogin: 'உள்நுழைவுக்கு திரும்பு',
    authResetYour: 'உங்கள்',
    authJoinAs: 'இந்த வகையில் சேரவும்',
    authFirstNameRequired: 'முதல் பெயர் அவசியம்',
    authLastNameRequired: 'கடைசி பெயர் அவசியம்',
    authMobileRequired: 'மொபைல் எண் அவசியம்',
    authMobileInvalid: 'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்',
    authEmailRequired: 'மின்னஞ்சல் முகவரி அவசியம்',
    authEmailInvalid: 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    authPasswordRequired: 'கடவுச்சொல் அவசியம்',
    authPasswordMin: 'குறைந்தது 6 எழுத்துக்கள்',
    authPasswordsNoMatch: 'கடவுச்சொற்கள் பொருந்தவில்லை',
    authAddressRequired: 'வீட்டு முகவரி அவசியம்',
    authRequired: 'தேவையானது',
    authOtpSentWhatsapp: 'OTP உங்கள் WhatsApp-க்கு அனுப்பப்பட்டது!',
    authOtpAutoSendFailed: 'WhatsApp OTP தானாக அனுப்ப முடியவில்லை.',
    authUserRegistered: 'பயனர் வெற்றிகரமாக பதிவு செய்யப்பட்டார்! வரவேற்பு,',
    authRegistrationFailed: 'பதிவு தோல்வியடைந்தது:',
    authGoogleFailed: 'Google உள்நுழைவு தோல்வியடைந்தது:',
    authGeolocationUnsupported: 'Geolocation ஆதரிக்கப்படவில்லை',
    authLocationDenied: 'இடம் அணுகல் மறுக்கப்பட்டது',
    authFirstName: 'முதல் பெயர்',
    authFirstNamePlaceholder: 'ரவி',
    authLastName: 'கடைசி பெயர்',
    authLastNamePlaceholder: 'குமார்',
    authMobileNumber: 'மொபைல் எண்',
    authMobilePlaceholder: '9876543210',
    authEmailPlaceholderGeneric: 'email@example.com',
    authAddress: 'முகவரி',
    authUseCurrentLocation: 'தற்போதைய இடத்தை பயன்படுத்து',
    authLocating: 'இடம் கண்டறிகிறது...',
    authAddressPlaceholder: 'நகரம்/மாவட்டத்துடன் முழு முகவரி',
    authCityPlaceholder: 'நகரம் (உ.பி. சென்னை)',
    authDepartment: 'துறை',
    authSelectDepartment: 'துறையைத் தேர்வு செய்க',
    authEmail: 'மின்னஞ்சல்',
    authConfirm: 'உறுதிப்படுத்து',
    authSignUpNow: 'இப்போது பதிவு செய்யவும்',
    authAlreadyMember: 'ஏற்கனவே உறுப்பினரா?',
    authNoVerificationDetails: 'சரிபார்ப்பு விவரங்கள் இல்லை. தயவுசெய்து மீண்டும் முயற்சிக்கவும்.',
    authVerificationComplete: 'சரிபார்ப்பு முடிந்தது! மாற்றப்படுகிறது...',
    authSessionStartFailed: 'அமர்வு துவங்க முடியவில்லை. கைமுறையாக உள்நுழையவும்.',
    authWhatsappOtpSent: 'WhatsApp OTP அனுப்பப்பட்டது!',
    authEmailOtpSent: 'மின்னஞ்சல் OTP அனுப்பப்பட்டது!',
    authEnterValidOtp: 'சரியான 6 இலக்க OTP-ஐ உள்ளிடவும்',
    authMobileVerified: 'மொபைல் வெற்றிகரமாக சரிபார்க்கப்பட்டது!',
    authEmailVerified: 'மின்னஞ்சல் வெற்றிகரமாக சரிபார்க்கப்பட்டது!',
    authCityHubAdded: 'நீங்கள் உங்கள் City Alert Hub-இல் சேர்க்கப்பட்டுள்ளீர்கள்!',
    authTwoFactorTitle: 'இரு-அங்கீகார உள்நுழைவு',
    authAccountVerificationTitle: 'கணக்கு சரிபார்ப்பு',
    authVerifyEmailSubtitle: 'உங்கள் கணக்கை அணுக மின்னஞ்சலை சரிபார்க்கவும்.',
    authVerifyMobileEmailSubtitle: 'தொடர மொபைல் எண் மற்றும் மின்னஞ்சலை சரிபார்க்கவும்.',
    authMobileVerification: 'மொபைல் சரிபார்ப்பு',
    authSending: 'அனுப்புகிறது...',
    authSendOtp: 'OTP அனுப்பு',
    authVerifyMobile: 'மொபைலை சரிபார்',
    authEmailVerification: 'மின்னஞ்சல் சரிபார்ப்பு',
    authVerifyEmail: 'மின்னஞ்சலை சரிபார்',
    authSecureOfficialPortal: 'பாதுகாப்பான அதிகாரி போர்டல்',
    authLoginHeadingLine1: 'குடிமக்களை வலுப்படுத்தி,',
    authLoginHeadingLine2: 'அதிகாரிகளை இயக்குகிறது.',
    authLoginSubtext: 'பாதுகாப்பான, புத்திசாலியான மற்றும் நிலைத்த சமுதாயத்தை உருவாக்கும் வலையமைப்பில் சேருங்கள்.',
    authVerified: 'சரிபார்க்கப்பட்டது',
    authGovPlatform: 'அரசு தளம்',
    authSecurity: 'பாதுகாப்பு',
    authEncryption: '256-பிட் குறியாக்கம்',
    authRegainAccessTo: 'மீண்டும் அணுகலை பெறுங்கள்',
    authSecureProcess: 'பாதுகாப்பான செயல்முறை',
    authRegisterHeadingLine1: 'இயக்கத்தில் சேருங்கள்',
    authRegisterHeadingLine2: 'சிறந்த நகரங்களுக்கு.',
    authRegisterSubtext: 'சுத்தமான நகரத்தை உருவாக்க உங்கள் உள்ளூர் நிர்வாகத்துக்கு உதவ இன்று பதிவு செய்யுங்கள்.',
  },
  ml: {
    brandName: 'നഗർ അലർട്ട് ഹബ്',
    brandLogoAlt: 'നഗർ അലർട്ട് ഹബ് ലോഗോ',
    civicTagline: 'സിവിക് ഇന്റലിജൻസ് പ്ലാറ്റ്ഫോം',
    home: 'ഹോം',
    features: 'സവിശേഷതകൾ',
    whatsapp: 'വാട്ട്സ്ആപ്പ്',
    about: 'ഞങ്ങളേക്കുറിച്ച്',
    login: 'ലോഗിൻ',
    logout: 'ലോഗൗട്ട്',
    switchTheme: 'തീം മാറ്റുക',
    platform: 'പ്ലാറ്റ്ഫോം',
    company: 'കമ്പനി',
    connect: 'കണക്റ്റ്',
    howItWorks: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    forMunicipalities: 'മുനിസിപ്പാലിറ്റികൾക്കായി',
    successStories: 'വിജയകഥകൾ',
    aboutUs: 'ഞങ്ങളേക്കുറിച്ച്',
    privacyPolicy: 'സ്വകാര്യത നയം',
    termsOfService: 'സേവന നിബന്ധനകൾ',
    rightsReserved: '© 2026 Nagar Alert Hub. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതമാണ്.',
    madeWithIndia: 'ഇന്ത്യയിൽ ❤️ ഉപയോഗിച്ച് നിർമ്മിച്ചത്',
    language: 'ഭാഷ',
    authForgotPassword: 'പാസ്‌വേഡ് മറന്നോ?',
    authOtpSendFailed: 'സ്ഥിരീകരണ OTP അയയ്ക്കുന്നതിൽ പരാജയപ്പെട്ടു',
    authCredentialsVerified: 'നിങ്ങളുടെ വിവരങ്ങൾ സ്ഥിരീകരിച്ചു! ദയവായി ഇമെയിലിൽ വന്ന OTP നൽകുക.',
    authInvalidCredentials: 'തെറ്റായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്. ദയവായി വീണ്ടും ശ്രമിക്കുക അല്ലെങ്കിൽ രജിസ്റ്റർ ചെയ്യുക.',
    authTooManyRequests: 'വളരെ അധികം പരാജയപ്പെട്ട ശ്രമങ്ങൾ. ദയവായി പാസ്‌വേഡ് റീസെറ്റ് ചെയ്യുക അല്ലെങ്കിൽ ശേഷം ശ്രമിക്കുക.',
    authSecureAccessTagline: 'പൗരന്മാർക്കും ഉദ്യോഗസ്ഥർക്കും സുരക്ഷിത പ്രവേശനം',
    authCitizenPortal: 'പൗരൻ പോർട്ടൽ',
    authAdminOfficial: 'അഡ്മിൻ/ഉദ്യോഗസ്ഥൻ',
    authEmailAddress: 'ഇമെയിൽ വിലാസം',
    authOfficialIdEmail: 'ഓഫീഷ്യൽ ഐഡി / ഇമെയിൽ',
    authEmailPlaceholder: 'you@example.com',
    authOfficialEmailPlaceholder: 'official@nagaralert.gov.in',
    authPassword: 'പാസ്‌വേഡ്',
    authPasswordLower: 'പാസ്‌വേഡ്',
    authSecureLogin: 'സുരക്ഷിത ലോഗിൻ',
    authNewToPlatform: 'Nagar Alert Hub-ലേക്ക് പുതുതാണോ?',
    authRegisterAccount: 'അക്കൗണ്ട് രജിസ്റ്റർ ചെയ്യുക',
    authResetLinkSent: 'പാസ്‌വേഡ് റീസെറ്റ് ലിങ്ക് നിങ്ങളുടെ ഇമെയിലിലേക്ക് അയച്ചു.',
    authSecureResetPortal: 'സുരക്ഷിത റീസെറ്റ് പോർട്ടൽ',
    authYourAccount: 'നിങ്ങളുടെ അക്കൗണ്ട്.',
    authResetHelpText: 'പാസ്‌വേഡ് സുരക്ഷിതമായി റീസെറ്റ് ചെയ്യാൻ ലളിതമായ ഘട്ടങ്ങൾ പിന്തുടരുക.',
    authCitizen: 'പൗരൻ',
    authOfficial: 'ഉദ്യോഗസ്ഥൻ',
    authRegisteredEmail: 'രജിസ്റ്റർ ചെയ്ത ഇമെയിൽ വിലാസം',
    authEmailPlaceholderGeneric: 'email@example.com',
    authResetSecurityNote: 'സുരക്ഷയ്ക്കായി റീസെറ്റ് ലിങ്കുകൾ ഇമെയിൽ വഴി അയയ്ക്കപ്പെടുന്നു.',
    authSendResetLink: 'റീസെറ്റ് ലിങ്ക് അയയ്ക്കുക',
    authRememberedPassword: 'പാസ്‌വേഡ് ഓർമ്മയായി?',
    authBackToLogin: 'ലോഗിനിലേക്ക് മടങ്ങുക',
    authResetYour: 'നിങ്ങളുടെ',
    authJoinAs: 'എന്ന നിലയിൽ ചേരുക',
    authFirstNameRequired: 'പേരിന്റെ ആദ്യഭാഗം ആവശ്യമാണ്',
    authLastNameRequired: 'പേരിന്റെ അവസാനഭാഗം ആവശ്യമാണ്',
    authMobileRequired: 'മൊബൈൽ നമ്പർ ആവശ്യമാണ്',
    authMobileInvalid: 'സാധുവായ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക',
    authEmailRequired: 'ഇമെയിൽ വിലാസം ആവശ്യമാണ്',
    authEmailInvalid: 'സാധുവായ ഇമെയിൽ വിലാസം നൽകുക',
    authPasswordRequired: 'പാസ്‌വേഡ് ആവശ്യമാണ്',
    authPasswordMin: 'കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ',
    authPasswordsNoMatch: 'പാസ്‌വേഡുകൾ ഒത്തുപോകുന്നില്ല',
    authAddressRequired: 'വീട്ടുവിലാസം ആവശ്യമാണ്',
    authRequired: 'ആവശ്യം',
    authOtpSentWhatsapp: 'OTP നിങ്ങളുടെ WhatsApp-ലേക്ക് അയച്ചു!',
    authOtpAutoSendFailed: 'WhatsApp OTP സ്വയമേവ അയയ്ക്കാൻ കഴിഞ്ഞില്ല.',
    authUserRegistered: 'ഉപയോക്താവ് വിജയകരമായി രജിസ്റ്റർ ചെയ്തു! സ്വാഗതം,',
    authRegistrationFailed: 'രജിസ്ട്രേഷൻ പരാജയപ്പെട്ടു:',
    authGoogleFailed: 'Google സൈൻ-ഇൻ പരാജയപ്പെട്ടു:',
    authGeolocationUnsupported: 'Geolocation പിന്തുണയ്ക്കുന്നില്ല',
    authLocationDenied: 'ലൊക്കേഷൻ അനുമതി നിരസിച്ചു',
    authFirstName: 'പേരിന്റെ ആദ്യഭാഗം',
    authFirstNamePlaceholder: 'റാഹുൽ',
    authLastName: 'പേരിന്റെ അവസാനഭാഗം',
    authLastNamePlaceholder: 'കുമാർ',
    authMobileNumber: 'മൊബൈൽ നമ്പർ',
    authMobilePlaceholder: '9876543210',
    authAddress: 'വിലാസം',
    authUseCurrentLocation: 'നിലവിലെ ലൊക്കേഷൻ ഉപയോഗിക്കുക',
    authLocating: 'ലൊക്കേഷൻ കണ്ടെത്തുന്നു...',
    authAddressPlaceholder: 'നഗരം/സംസ്ഥാനത്തോട് കൂടിയ മുഴുവൻ വിലാസം',
    authCityPlaceholder: 'നഗരം (ഉദാ. കൊച്ചി)',
    authDepartment: 'വകുപ്പ്',
    authSelectDepartment: 'വകുപ്പ് തിരഞ്ഞെടുക്കുക',
    authEmail: 'ഇമെയിൽ',
    authConfirm: 'സ്ഥിരീകരിക്കുക',
    authSignUpNow: 'ഇപ്പോൾ സൈൻ അപ്പ് ചെയ്യൂ',
    authAlreadyMember: 'ഇതിനകം അംഗമാണോ?',
    authNoVerificationDetails: 'സ്ഥിരീകരണ വിവരങ്ങൾ ലഭിച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.',
    authVerificationComplete: 'സ്ഥിരീകരണം പൂർത്തിയായി! റീഡയറക്ട് ചെയ്യുന്നു...',
    authSessionStartFailed: 'സെഷൻ ആരംഭിക്കാനായില്ല. ദയവായി മാനുവലായി ലോഗിൻ ചെയ്യുക.',
    authWhatsappOtpSent: 'WhatsApp OTP അയച്ചു!',
    authEmailOtpSent: 'ഇമെയിൽ OTP അയച്ചു!',
    authEnterValidOtp: 'സാധുവായ 6 അക്ക OTP നൽകുക',
    authMobileVerified: 'മൊബൈൽ വിജയകരമായി സ്ഥിരീകരിച്ചു!',
    authEmailVerified: 'ഇമെയിൽ വിജയകരമായി സ്ഥിരീകരിച്ചു!',
    authCityHubAdded: 'നിങ്ങളെ City Alert Hub-ലേക്ക് ചേർത്തു!',
    authTwoFactorTitle: 'ടു-ഫാക്ടർ ഓതന്റിക്കേഷൻ',
    authAccountVerificationTitle: 'അക്കൗണ്ട് സ്ഥിരീകരണം',
    authVerifyEmailSubtitle: 'നിങ്ങളുടെ അക്കൗണ്ടിലേക്ക് പ്രവേശിക്കാൻ ഇമെയിൽ സ്ഥിരീകരിക്കുക.',
    authVerifyMobileEmailSubtitle: 'തുടരാൻ മൊബൈൽ നമ്പറും ഇമെയിലും സ്ഥിരീകരിക്കുക.',
    authMobileVerification: 'മൊബൈൽ സ്ഥിരീകരണം',
    authSending: 'അയയ്ക്കുന്നു...',
    authSendOtp: 'OTP അയയ്ക്കുക',
    authVerifyMobile: 'മൊബൈൽ സ്ഥിരീകരിക്കുക',
    authEmailVerification: 'ഇമെയിൽ സ്ഥിരീകരണം',
    authVerifyEmail: 'ഇമെയിൽ സ്ഥിരീകരിക്കുക',
    authSecureOfficialPortal: 'സുരക്ഷിത ഔദ്യോഗിക പോർട്ടൽ',
    authLoginHeadingLine1: 'പൗരന്മാരെ ശക്തിപ്പെടുത്തി,',
    authLoginHeadingLine2: 'അധികാരികളെ സജ്ജമാക്കുന്നു.',
    authLoginSubtext: 'സുരക്ഷിതവും ബുദ്ധിമാനുമായ സ്ഥിരതയുള്ള സമൂഹങ്ങൾ നിർമ്മിക്കുന്ന നെറ്റ്‌വർക്കിലേക്ക് ചേരൂ.',
    authVerified: 'സ്ഥിരീകരിച്ചത്',
    authGovPlatform: 'സർക്കാർ പ്ലാറ്റ്ഫോം',
    authSecurity: 'സുരക്ഷ',
    authEncryption: '256-ബിറ്റ് എൻക്രിപ്ഷൻ',
    authRegainAccessTo: 'വീണ്ടും ആക്‌സസ് നേടുക',
    authSecureProcess: 'സുരക്ഷിത പ്രക്രിയ',
    authRegisterHeadingLine1: 'പ്രസ്ഥാനത്തിൽ ചേരൂ',
    authRegisterHeadingLine2: 'മികച്ച നഗരങ്ങൾക്കായി.',
    authRegisterSubtext: 'ശുചിയായ നഗരം നിർമ്മിക്കാൻ നിങ്ങളുടെ പ്രാദേശിക ഭരണകൂടത്തെ സഹായിക്കാൻ ഇന്ന് തന്നെ സൈൻ അപ്പ് ചെയ്യൂ.',
  },
};

const LanguageContext = React.createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = React.useState(() => localStorage.getItem('language') || 'en');

  React.useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = React.useCallback(
    (key) => TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key,
    [language]
  );

  const value = React.useMemo(
    () => ({ language, setLanguage, t, languageOptions: LANGUAGE_OPTIONS }),
    [language, t]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
